common:
  model: ""
  batch_size: 16
  p_thresh: 3
  graph_pairs_dir: "/home/l/桌面/conv_graph/graphs_rn"
arch:
  keep_node: 1
  filters_1: 64
  filters_2: 64
  filters_3: 32
  tensor_neurons: 16
  bottle_neck_neurons: 16
  K: 10
train:
  epochs: 500
  train_sequences: ['00','01','02','03','04','05','06','07','09','10']
  eval_sequences: ["08",]
  dropout: 0
  learning_rate: 0.001
  weight_decay: 0.0005
  gpu: 0
  logdir: "./logs"
  node_num: 100
eva_batch:
  sequences: ["00","05"]
  output_path: "./eva"
  show: True
eva_pair:
  pair_file: ["./data/0.json","./data/250.json"]