common:
  model: "./model/model.pth"
  batch_size: 16
  p_thresh: 10
  graph_pairs_dir: ""
arch:
  keep_node: 1
  filters_1: 64
  filters_2: 64
  filters_3: 32
  tensor_neurons: 16
  bottle_neck_neurons: 16
train:
  epochs: 500
  fold: "00"
  dropout: 0
  learning_rate: 0.001
  weight_decay: 0.0005
  gpu: 0
  logdir: "./logs"
  node_num: 100
eva_batch:
  sequences: ["00","05"]
  output_path: "./eva"
  show: True
eva_pair:
  pair_file: ["./data/0.json","./data/250.json"]